services:
  - type: web
    name: reservas
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_DGXRwl4kBtC7@ep-shy-firefly-b5sbjmrd-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: NODE_ENV
        value: production
      - key: SINPE_IMAP_HOST
        value: imap.gmail.com
      - key: SINPE_IMAP_PORT
        value: "993"
      - key: SINPE_EMAIL_USER
        value: pampo32@gmail.com
      - key: SINPE_EMAIL_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: NYLAS_CLIENT_ID
        value: 4c11b10e-abe8-43b3-8765-d1feb79cd423
      - key: NYLAS_API_KEY
        value: nyk_v0_M0hOZUBmkau4XGjvPW8M0aeZF1OU2f3HLRUAg1Liqzogmc7eUODcpr6wuB4SgQkF
      - key: NYLAS_API_URI
        value: https://api.us.nylas.com
      - key: NYLAS_REDIRECT_URI
        value: https://reservascr.app/api/nylas/callback
